version: "3.8"

services:

  excuses:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: excuses
    restart: unless-stopped
    volumes:
      - ./logs:/var/www/html/logs
      - ./Assets/data:/var/www/html/Assets/data
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excuses.rule=Host(`excuses.apercheron.fr`)"
      - "traefik.http.routers.excuses.entrypoints=websecure"
      - "traefik.http.routers.excuses.tls.certresolver=letsencrypt"
      - "traefik.http.services.excuses.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true